# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 922722759680b68f224edf032ed53f57d728ae8a5d0beae468f3051077428b555b623a789aaf9a1397cbc1fa24be2a58c828bc39bc6c4ea866a45fa26418c26e

test:
  secret_key_base: b1d0d1f7afa65b54d5fcba17f27dee439917444f46345abf322f9b9999fcd2a08b8eb825cd577328735c22af56c71e367ba7a1b0a14d3b8dc58b2aceb8e7e899

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
